debug: release # gin release模式与debug模式切换
port: 8080
limit: 10
cors:
  allowOrigins:
    - http://127.0.0.1:8080
  allowMethods: POST,GET,OPTIONS,DELETE,PUT
  allowHeaders: Content-Type,AccessToken,X-CSRF-Token,Authorization,Token,X-Token,X-User-Id
  exposeHeaders: Content-Length,Access-Control-Allow-Origin,Access-Control-Allow-Headers,Content-Type,New-Token,New-Expires-At
  allowCredentials: "true"
  maxAge: 43200
redis:
  instances:
    - name: default
      addr: 127.0.0.1
      port: 6379
      password: ""
      dbs:
        - db: 0
          pool_size: 50
        - db: 1
          pool_size: 30
        - db: 2
          pool_size: 20
        - db: 3
          pool_size: 10
        - db: 4
          pool_size: 5
        - db: 5
          pool_size: 5
        - db: 6
          pool_size: 5
        - db: 7
          pool_size: 5
        - db: 8
          pool_size: 5
        - db: 9
          pool_size: 5

zap:
  director: log
  level: info
  maxAge: 3
  maxSize: 100
  maxBackups: 1
  format: console
  stackTraceKey: console
  encodeLevel: LowercaseLevelEncoder
  logInConsole: true
  showLine: true