debug: release # gin release模式与debug模式切换
port: 8080
limit: 10
cors:
  allowOrigins:
    - http://127.0.0.1:8080
  allowMethods: POST,GET,OPTIONS,DELETE,PUT
  allowHeaders: Content-Type,AccessToken,X-CSRF-Token,Authorization,Token,X-Token,X-User-Id
  exposeHeaders: Content-Length,Access-Control-Allow-Origin,Access-Control-Allow-Headers,Content-Type,New-Token,New-Expires-At
  allowCredentials: "true"
  maxAge: 43200
redis:
  instances:
    - name: default
      addr: 127.0.0.1
      port: 6379
      password: ""
      dbs: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
zap:
  director: log
  level: info
  maxAge: 3
  maxSize: 100
  maxBackups: 3
  format: console
  stackTraceKey: console
  encodeLevel: LowercaseLevelEncoder
  prefix:
  logInConsole: true
  showLine: true